config/routes.rb
Rails.application.routes.draw do
  get  '/home',    to: 'welcome#home'
  get  '/about',   to: 'about#about'
  get  '/contacts', to: 'static_pages#contacts'
  get  '/service',   to: 'foods#index'
  get  '/blog', to: 'static_pages#blog'
  get '/order_items', to: 'carts#index'

  root 'welcome#home'

  resources :categories
  resources :foods
  resources :order_items
  resources :carts

  resources :users do
    resources :orders
  end

  namespace :administrator do
    resources :orders, :foods, :users, :categories
  end
  
  namespace :api do 
    namespace :v1 do 
      resources :foods
    end 
  end 
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  post 'checkout' => 'checkout#show', as: :checkout
  get '/payment/processed' => 'order#create', as: :get_payment_completed
  post 'payment' => 'order#create', as: :payment
  post '/payment/processed' => 'order#create', as: :payment_completed

  post 'carts/checkout' => 'carts#checkout', as: :cart_checkout

  get 'administrator' => 'administrator#show', as: :dashboard

  patch 'order_status' => 'administrator/orders#update', as: :order_status

end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :category

  has_many :order_items
  has_many :orders, through: :order_items
  
  has_attached_file :food_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "default_food.jpg"
  validates_attachment_size :food_image, :in => 0.megabytes..10.megabytes
  validates_attachment_content_type :food_image, :content_type => /\Aimage\/.*\Z/

  private

    def ensure_not_referenced_by_any_order_item
      unless order_items.empty?
        errors.add(:base, 'Order Items present')
        throw :abort
      end
    end
end

app/controllers/administrator/base_controller.rb
class Administrator::BaseController < ApplicationController
  before_action :authorize_admin, only: [:show, :update]
  layout 'admin'
end

app/controllers/administrator/categories_controller.rb
class Administrator::CategoriesController < Administrator::BaseController

  def index
    @categories = Category.all.paginate(page: params[:page], per_page: 10)
  end
end

app/controllers/administrator/foods_controller.rb
class Administrator::FoodsController < Administrator::BaseController  

  def index
    @foods = Food.all.order(created_at: :desc)
  end
end

app/controllers/administrator/orders_controller.rb
class Administrator::OrdersController < Administrator::BaseController
  
  def index
    @orders = Order.all.paginate(page: params[:page], per_page: 10)
  end

  def update
    set_order
    @order.update(order_params)
    UserMailer.status_email(@order).deliver_now
    redirect_to dashboard_path
  end

  private

    def set_order
      @order = Order.find(params[:order_id])
    end

    def order_params
      params[:order].permit(:payment_status)
    end
end

app/controllers/administrator/users_controller.rb
class Administrator::UsersController < Administrator::BaseController

  def index
    @users = User.all.paginate(page: params[:page], per_page: 10).order(created_at: :desc)
  end
end

app/controllers/administrator_controller.rb
class AdministratorController < ApplicationController
  before_action :authorize_admin, only: [:show, :update]
  layout 'admin'
end

app/controllers/api/v1/foods_controller.rb
class Api::V1::FoodsController < ApiController

  def index
    @foods = Food.all.order(created_at: :asc)
    render json: { data: @foods }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authorize_admin,
                only: [:create, :destroy, :update]
  before_action :set_food, only: [:show, :edit, :update, :destroy]


  def index
    @foods = Food.all.order(created_at: :asc)
  end

  def new
    @food = Food.new
  end

  def edit
  end

  def create
    @food = {}
    upload_image
    @food = Food.create(food_params)
    flash[:success] = "#{@food.name} has been added successfully."
    redirect_to dashboard_path
  end

  def show
  end

  def update
    upload_image if food_params[:food_image]
    if @food
      save_food
    else
      flash[:error] = "An error occured. Try adding #{@food.name} again."
    end
  end

  def destroy
    if @food
      @food.destroy
      flash[:success] = "#{food.name} has been deleted."
      redirect_to dashboard_path
    else
      flash[:error] = "An error occured. Try deleting #{@food.name} again."
    end
  end

  private

    def set_food
      @food = Food.find(params[:id])
    end

    def food_params
      params.require(:food).permit(:id, :name, :description, :price, :category_id, :food_image)
    end

    def upload_image
      image = food_params[:food_image]
      @food_image_url = false
      if image
        @upload = {}
        @upload[:food_image] = Cloudinary::Uploader.upload(image)
        @food_image_url = @upload[:food_image]['url']
        @food[:food_image_file_name] = @food_image_url
      end
      @food_image_url
    end

    def save_food
      @food[:food_image_file_name] = @food_image_url
      @food.update(food_params)
      flash[:success] = "#{@food.name} has been updated successfully."
      redirect_to dashboard_path
    end
end

app/views/administrator/foods/_foods.html.haml
.container.text-center
  %h2 All foods
.container.text-center
  .body
    %table.table-striped
      %thead
        %tr
          %th{ "data-field" => "id" } Name
          %th{ "data-field" => "name" } Description
          %th{ "data-field" => "price" } Item Price
          %th{ "data-field" => "price" } Category
          %th{ "data-field" => "price" } Updated
          %th{ "data-field" => "price" }
      %tbody
        - @foods.each do |food|
          %a{ :href => "/>" }
            %tr
              %td= link_to "#{food.name}", edit_food_path(food.id)
              %td= food.description
              %td= food.price
              %td= !food.category.nil? ? food.category.title : 'none yet'
              %td= food.updated_at.strftime("%Y %e %d")
              %td
                = button_to food_path(food.id), :class => "clear-button", method: :delete do
                  %i.material-icons clear
  .footer
    .row
      %a.btn-danger{ :href => '/foods/new' }
        Add food
        %i.fas.fa-plus-circle

app/views/administrator/foods/index.html.haml
.container.text-center
  %h2 All foods
.container.text-center
  .body
    %table.table-striped.col-sm-12
      %thead
        %tr
          %th Name
          %th Description
          %th Item Price
          %th Category
          %th Updated
          %th
      %tbody
        - @foods.each do |food|
          %a{ :href => "/>" }
            %tr
              %td= link_to "#{food.name}", edit_food_path(food.id)
              %td= food.description
              %td= food.price
              %td= food.category.present? ? food.category.title : 'none yet'
              %td= food.updated_at.strftime("%Y %e %d")
              %td
                = button_to food_path(food.id), :class => "clear-button", method: :delete do
                  %i.material-icons clear
  .footer
    .row
      %a.btn-danger{ :href => '/foods/new' }
        Add food
        %i.fas.fa-plus-circle