config/routes.rb
Rails.application.routes.draw do
  get  '/home',    to: 'welcome#home'
  get  '/about',   to: 'about#about'
  get  '/contacts', to: 'static_pages#contacts'
  get  '/service',   to: 'foods#index'
  get  '/blog', to: 'static_pages#blog'
  get '/order_items', to: 'carts#index'

  root 'welcome#home'

  resources :categories
  resources :foods
  resources :order_items
  resources :carts

  resources :users do
    resources :orders
  end

  namespace :administrator do
    resources :orders, :foods, :users, :categories
  end
  
  namespace :api do 
    namespace :v1 do 
      resources :foods
    end 
  end 
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  post 'checkout' => 'checkout#show', as: :checkout
  get '/payment/processed' => 'order#create', as: :get_payment_completed
  post 'payment' => 'order#create', as: :payment
  post '/payment/processed' => 'order#create', as: :payment_completed

  post 'carts/checkout' => 'carts#checkout', as: :cart_checkout

  get 'administrator' => 'administrator#show', as: :dashboard

  patch 'order_status' => 'administrator/orders#update', as: :order_status

end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :order_items, dependent: :destroy

  def add_food(food)
    current_item = order_items.find_by(food_id: food.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = order_items.build(food_id: food.id)
    end
    current_item
  end

  def total_price
    order_items.to_a.sum { |item| item.total_price }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  
  def index
    @cart = Cart.find(session[:cart_id])
  end

  def show
  end

  def new
    @cart = Cart.new
  end

  def edit
  end
  
  def create
    @cart = Cart.new(cart_params)

    if @cart.save
      redirect_to @cart, notice: 'Cart was successfully created.'
    else
      render :new
    end
  end

  def update
    if @cart.update(cart_params)
      redirect_to @cart, notice: 'Cart was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    redirect_to root_path, notice: 'Your cart is currently empty'
  end

  private
  
    def set_cart
      @cart = Cart.find(session[:cart_id])
    end

    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_index_url, notice: 'Invalid cart'
    end
end

app/views/carts/index.html.haml
= javascript_include_tag 'application', 'data-turbolinks-track' => false
.header-1-wrap
  = render 'layouts/top_header'
= render 'layouts/flash_messages'
.container
  .pad-bottom
    - if @cart.order_items.length == 0
      %p.text-center Your cart is empty
    - else
      %table.table.table-striped
        %thead.table-head
          %tr
            %th{ "data-field" => "id" } Food id#
            %th{ "data-field" => "name" } Name
            %th{ "data-field" => "description" } Description
            %th{ "data-field" => "quantity" } Quantity
            %th{ "data-field" => "price" } Price
            %th{ "data-field" => "line total" } Line Total
        %tbody
          - @cart.order_items.each do |item|
            - food_id = item.food.id
            %tr
              %td= item.food.id
              %td{ id: "food_name_#{food_id}" }= item.food.name
              %td{ id: "food_desc_#{food_id}" }= item.food.description
              %td{ id: "food_qty_#{food_id}" }= item.quantity
              %td{ id: "food_unit_price_#{food_id}" }= item.food.price
              %td
                $
                %span.line-total= item.total_price
              %td
                = button_to order_item_path(item.id), :class => 'clear-button', method: :delete  do
                  %i.material-icons clear
        %tfoot.table-foot
          %tr
            %td
            %td
            %td
            %td
            %td
            %td Subtotal
            %td#total
              $#{@cart.total_price}
      = button_to 'Checkout', checkout_path, :class => 'btn btn-info'

app/views/carts/show.html.haml
= render 'carts/index'